CREATE TABLE NEWS (
  ID NUMBER not null,
  TITLE VARCHAR2(120 CHAR) not null,
  DATETIME DATE not null,
  BRIEF VARCHAR2(700 CHAR) not null,
  CONTENT VARCHAR2(2048 CHAR) not null
);

ALTER TABLE NEWS ADD (
  CONSTRAINT news_pk PRIMARY KEY (ID));

CREATE SEQUENCE news_seq START WITH 1 INCREMENT BY 1;