CREATE TABLE NEWS (
  ID NUMBER not null,
  TITLE VARCHAR2(120 CHAR),
  DATETIME DATE,
  BRIEF VARCHAR2(700 CHAR),
  CONTENT VARCHAR2(2048 CHAR)
);

ALTER TABLE NEWS ADD (
  CONSTRAINT news_pk PRIMARY KEY (ID));

CREATE SEQUENCE news_seq START WITH 1 INCREMENT BY 1;