DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS news;
DROP SEQUENCE IF EXISTS NEWS_SEQ;
DROP SEQUENCE IF EXISTS ROLES_SEQ;
DROP SEQUENCE IF EXISTS USERS_SEQ;

-- create table News
CREATE TABLE NEWS (
  ID NUMBER not null,
  TITLE VARCHAR2(120 CHAR) not null,
  DATETIME DATE not null,
  BRIEF VARCHAR2(700 CHAR) not null,
  CONTENT VARCHAR2(2048 CHAR) not null
);

CREATE SEQUENCE news_seq START WITH 1 INCREMENT BY 1;

-- users
CREATE TABLE USERS
(
    ID INT PRIMARY KEY NOT NULL,
    LOGIN VARCHAR2(100) NOT NULL,
    PASSWORD VARCHAR2(100) NOT NULL,
    ROLE_ID INT NOT NULL
);
CREATE UNIQUE INDEX USERS_LOGIN_uindex ON USERS (LOGIN);
CREATE sequence USERS_SEQ START WITH 1 INCREMENT BY 1;

-- roles
CREATE TABLE ROLES
(
    ID INT PRIMARY KEY NOT NULL,
    NAME VARCHAR2(200) NOT NULL
);
CREATE UNIQUE INDEX ROLES_ID_uindex ON ROLES (ID);
CREATE UNIQUE INDEX ROLES_NAME_uindex ON ROLES (NAME);
CREATE sequence ROLES_SEQ START WITH 1 INCREMENT BY 1;

-- insert roles
INSERT INTO ROLES (ID, NAME) VALUES (ROLES_SEQ.nextval, 'ROLE_ADMIN');
INSERT INTO ROLES (ID, NAME) VALUES (ROLES_SEQ.nextval, 'ROLE_USER');

-- insert users
INSERT INTO USERS (ID, LOGIN, PASSWORD, ROLE_ID) VALUES (USERS_SEQ.nextval, 'admin', 'admin', 1);
INSERT INTO USERS (ID, LOGIN, PASSWORD, ROLE_ID) VALUES (USERS_SEQ.nextval, 'user', 'user', 2);
