-- create table News
CREATE TABLE NEWS (
  ID NUMBER not null,
  TITLE VARCHAR2(120 CHAR) not null,
  DATETIME DATE not null,
  BRIEF VARCHAR2(700 CHAR) not null,
  CONTENT VARCHAR2(2048 CHAR) not null
);

ALTER TABLE NEWS ADD (
  CONSTRAINT news_pk PRIMARY KEY (ID));

CREATE SEQUENCE news_seq START WITH 1 INCREMENT BY 1;

-- users
CREATE TABLE ADKDB.USERS
(
    ID INT PRIMARY KEY NOT NULL,
    LOGIN VARCHAR2(100) NOT NULL,
    PASSWORD VARCHAR2(100) NOT NULL,
    ROLE_ID INT NOT NULL
);
CREATE UNIQUE INDEX USERS_LOGIN_uindex ON ADKDB.USERS (LOGIN);
CREATE sequence USERS_SEQ START WITH 1 INCREMENT BY 1;

-- roles
CREATE TABLE ADKDB.ROLES
(
    ID INT PRIMARY KEY NOT NULL,
    NAME VARCHAR2(200) NOT NULL
);
CREATE UNIQUE INDEX ROLES_ID_uindex ON ADKDB.ROLES (ID);
CREATE UNIQUE INDEX ROLES_NAME_uindex ON ADKDB.ROLES (NAME);
CREATE sequence ROLES_SEQ START WITH 1 INCREMENT BY 1;

-- insert roles
INSERT INTO ROLES (ID, NAME) VALUES (ROLES_SEQ.nextval, 'ROLE_ADMIN');
INSERT INTO ROLES (ID, NAME) VALUES (ROLES_SEQ.nextval, 'ROLE_USER');

-- insert users
INSERT INTO USERS (ID, LOGIN, PASSWORD, ROLE_ID) VALUES (USERS_SEQ.nextval, 'admin', 'admin', 1);
INSERT INTO USERS (ID, LOGIN, PASSWORD, ROLE_ID) VALUES (USERS_SEQ.nextval, 'user', 'user', 2);
